apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-with-auth
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # We strip the prefix before it passes to our backend or our app wont load as it will get route /bears instead /
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - basic'

spec:
  ingressClassName: nginx
  rules:
  # change the IP below based on the DNS resolution of your LB (under kubectl get svc -n ingress-nginx)
  - host: bear.52.19.166.170.nip.io 
    http:
      paths:
      - path: /
      # bear(/|$)(.*)
        pathType: Prefix
        backend:
          service:
             name: bear-svc
             port:
                number: 80
  - host: moose.52.19.166.170.nip.io
    http:
      paths:
      - path: /
      #moose(/|$)(.*)
        pathType: Prefix
        backend:
          service:
             name: moose-svc
             port:
                number: 80
