apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music #from RELEASE NAME
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: 1  #from values
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: spring-music #from values
        image: yanivomc/spring-music:latest #from values
        ports:
        - containerPort: 8080
---

kind: Service     
apiVersion: v1     
metadata:
  name: spring-service #from RELEASE NAME
spec:
  selector:
    app: music    
  type: LoadBalancer  #from values
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 8080
