apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.Deployment_name}} 
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.Deployment.replicas_number}}  
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: spring-music
        image: {{ .Values.Deployment.image_name}}
        ports:
        - containerPort: 8080
---

kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Values.service.Service_name}} 
spec:
  selector:
    app: music    
  type: {{ .Values.service.selector_type}}  
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}

---


service:
  Service_name: my-service
  selector_type: LoadBalancer
  port: 80
  targetPort: 8080
Deployment:
  Deployment_name: spring-music
  replicas_number: 1
  image_name: yanivomc/spring-music:latest
