######DEPLOYMENT#######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.Deployment.replicas_number}}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: spring-music
        image: {{ .Values.Deployment.repo }}/{{ .Values.Deployment.image }}:{{ .Values.Deployment.tag }}
        ports:
        - containerPort: 8080
---
######SERVICES#####
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: music
  type: {{ .Values.service.selector_type}}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}

---

#####VALUES#########
service:
  Service_name: my-service
  selector_type: LoadBalancer
  port: 80
  targetPort: 8080
Deployment:
  Deployment_name: spring-music
  replicas_number: 1
  repo: yanivomc
  tag: latest
  image: spring-music
