apiVersion: v1
kind: Pod
metadata:
  name: mypods
spec:
  containers:
  - name: animals
    image: upergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: /data
  - name: springapp
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /app/data
  volumes:
  - name: app-storage
    hostPath: /Desktop/storage_app
